TEMPLATE	= app
HEADERS		= ../include/controlcenter.h
FORMS		= controlcenter.ui
SOURCES		= controlcenter.cpp main.cpp fx2_download.cpp fx3_download.cpp streamer.cpp
RESOURCES	= controlcenter.qrc
LIBS		+= -L$$PWD/../lib -lcyusb -lusb-1.0
QMAKE_RPATHDIR += $$PWD/../lib
QT		+= widgets network
TARGET		= cyusb
DESTDIR		= ../bin
